<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_IR A PAGAR S 7.30</name>
   <tag></tag>
   <elementGuidId>6e9da4d3-2a81-4261-9e2b-fc0b2724a6f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-pagar-listar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-pagar-listar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>676b0fb2-cc57-4003-b97e-000e02fe72d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-pagar-listar</value>
      <webElementGuid>632633a8-2090-4475-a0c6-d8d314b3ee4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>7.30</value>
      <webElementGuid>c6f2af14-1091-46ed-99d8-108a9383f0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4cd79c25-4bd0-48b7-8416-587a932028fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning</value>
      <webElementGuid>8336f92f-93a7-42ea-971a-479eeb22213d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IR A PAGAR S/ 7.30</value>
      <webElementGuid>a5bc0465-8dcd-4541-ad6f-c76900afe028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-pagar-listar&quot;)</value>
      <webElementGuid>b96ccb48-9826-4513-9a2f-a3f5913ccc76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-pagar-listar']</value>
      <webElementGuid>1025e590-a197-4326-91a1-0f74c639ecc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_pagar']/button</value>
      <webElementGuid>e0b81194-f65c-4db2-be81-4fd6df9d1fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Siguiente'])[1]/following::button[1]</value>
      <webElementGuid>28dfca1a-dd2b-4b85-aed4-4e9141d35a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anterior'])[1]/following::button[1]</value>
      <webElementGuid>2aa2092b-2e9f-4a2a-a9ee-05988c13f42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿A dónde retornamos el cargo adjunto ?'])[1]/preceding::button[2]</value>
      <webElementGuid>615ab5dd-7541-4a04-9fd8-05dc02a3e30e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de entrega'])[3]/preceding::button[2]</value>
      <webElementGuid>80231ce5-5dc7-4c9a-972f-7bc0f32899dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='IR A PAGAR S/ 7.30']/parent::*</value>
      <webElementGuid>a38b0835-9ef7-4ae9-be45-b2ae2cdf4e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>d798f40a-61ad-485b-8997-c938a858730b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-pagar-listar' and @type = 'button' and (text() = 'IR A PAGAR S/ 7.30' or . = 'IR A PAGAR S/ 7.30')]</value>
      <webElementGuid>cb56c010-55a2-4d0e-88b1-d4f8a318a3e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
