<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CONTINUE</name>
   <tag></tag>
   <elementGuidId>d97e5652-80a6-4811-820b-12998aa351a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_aceptar_tipo_envio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_aceptar_tipo_envio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>903289c3-431d-4c20-a958-25cb8d73f863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_aceptar_tipo_envio</value>
      <webElementGuid>6c3dd1b6-0413-414f-9225-2d6333491fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2684b6d0-3828-4962-a299-74e763150fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning</value>
      <webElementGuid>78ee64b9-d12f-4da6-a8e7-14d3172f869f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTINUAR</value>
      <webElementGuid>e34448c9-a4da-4bb1-ac79-c3c5a8e572af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_aceptar_tipo_envio&quot;)</value>
      <webElementGuid>ef9d551d-ecbe-4a49-9e93-8c6cd8729cae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_aceptar_tipo_envio']</value>
      <webElementGuid>dfb06621-1de6-4893-896c-a9c7869947ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_tipo_envio']/button</value>
      <webElementGuid>35cd3e27-c55f-4164-82b4-de318d8db165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENVÍOS DE TARJETAS, AGENDAS Y CAJAS NAVIDEÑAS'])[1]/preceding::button[2]</value>
      <webElementGuid>f02d497c-3026-41e3-94c3-95ccb3904887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2774d04f-6edd-4277-bde5-8e6a16e69a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_aceptar_tipo_envio' and @type = 'button' and (text() = 'CONTINUAR' or . = 'CONTINUAR')]</value>
      <webElementGuid>22f70059-a042-43c8-bb78-9b39d991444f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
