<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OK_modal-backdrop fade in</name>
   <tag></tag>
   <elementGuidId>b6ab606c-5efc-4234-832d-2777090c17ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.modal-backdrop.fade.in</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5014cbe5-0e4f-46a0-ac49-6a6d71f4a14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-backdrop fade in</value>
      <webElementGuid>b7efe707-0289-4cff-b6f4-7e65a0bd9f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;modal-backdrop fade in&quot;]</value>
      <webElementGuid>b20bc52b-7562-441d-84b2-95dfafc739bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]</value>
      <webElementGuid>e0a4025d-1a7c-4bbe-a56f-4a2ebc085ac4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
