<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_LIMA - LIMA - BARRANCO</name>
   <tag></tag>
   <elementGuidId>564999e6-4208-4bb5-a66a-740be8c25413</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-5.cls_element_item.espacio_vista_xs_2.ret_domicilio > div.btn-group.bootstrap-select.form-control > button.btn.dropdown-toggle.form-control.selectpicker.btn-default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>49069b17-8cf3-4666-b6e9-6c2b4968e4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad174480-ee0e-46e5-9128-e707d18f1640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn dropdown-toggle form-control selectpicker btn-default</value>
      <webElementGuid>bbb97667-91ce-4c3e-ace3-a50a7efd99cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>b94185f4-569c-4d91-884e-0fba09e5cf3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>txt_descripcion_ubigeoCA</value>
      <webElementGuid>90e3afa8-5221-49b1-8c6c-04f919e504b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>LIMA - LIMA - BARRANCO</value>
      <webElementGuid>7a5b8da0-959d-4de1-afde-af9c5c5df444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LIMA - LIMA - BARRANCO </value>
      <webElementGuid>9fe21a45-6015-4391-b397-4e809db930d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formRetornoCargo&quot;)/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-5 cls_element_item espacio_vista_xs_2 ret_domicilio&quot;]/div[@class=&quot;btn-group bootstrap-select form-control&quot;]/button[@class=&quot;btn dropdown-toggle form-control selectpicker btn-default&quot;]</value>
      <webElementGuid>cb583322-1c88-46bf-bb8c-3d75468a97a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>ab31c0a4-56f3-48ba-857b-5a29ad47f16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRetornoCargo']/div/div[2]/div[4]/div/button</value>
      <webElementGuid>55ae5b14-643d-4ba3-9322-cbe242a1f8f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LIMA - LIMA - VILLA MARIA DEL TRIUNFO'])[2]/following::button[1]</value>
      <webElementGuid>8706c5be-f2e9-46f4-ac33-26aa3c4c64fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LIMA - LIMA - VILLA EL SALVADOR'])[2]/following::button[1]</value>
      <webElementGuid>6cbf1bea-815c-4878-8b05-8d806f05c1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Departamento - Provincia - Distrito'])[4]/preceding::button[1]</value>
      <webElementGuid>531856a7-40ab-48f5-84bc-d7ab49371f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>3e494cc0-3d7f-4849-a325-9e605b790e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'LIMA - LIMA - BARRANCO' and (text() = 'LIMA - LIMA - BARRANCO ' or . = 'LIMA - LIMA - BARRANCO ')]</value>
      <webElementGuid>0524f696-2823-4387-8ec3-a9d6af4c0c32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
