<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LIMA - LIMA - VILLA MARIA DEL TRIUNFO_df978c</name>
   <tag></tag>
   <elementGuidId>1f72012a-9f9e-45ea-9d45-20bc0f196eed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_direccion_entregaCA']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_direccion_entregaCA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1b72578-be88-4320-846d-046a8a9627c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f7bb5b84-44ee-465b-af80-035d82bc3fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_direccion_entregaCA</value>
      <webElementGuid>86e73a66-73e1-4d58-a52d-25e4f787b353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_direccion_entregaCA</value>
      <webElementGuid>f7331ea8-c9df-4968-8307-1dc8479fef32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Dirección de entrega</value>
      <webElementGuid>67fc8a84-ac20-4736-ad91-c2f4830d5ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-first-name form-control msg_alert_tt inputRE validMaxConsignado</value>
      <webElementGuid>88873d30-a29c-4c5e-9a33-45aa2701bc04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>00d9acda-c9e2-4e7e-bd60-7285006af9b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>189f02a6-0b31-44b7-a6a6-8ea7d63a06cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_direccion_entregaCA&quot;)</value>
      <webElementGuid>088d4097-27d0-4378-8fe2-46baa03b5103</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_direccion_entregaCA']</value>
      <webElementGuid>e1f5e23b-4252-49a3-89e2-dacd2da9f19f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRetornoCargo']/div[2]/div/div[2]/input</value>
      <webElementGuid>95e2a090-de07-44e9-bdc2-54f909cbd676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>344b8398-1d87-48f1-b975-8d7f705a2daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txt_direccion_entregaCA' and @id = 'txt_direccion_entregaCA' and @placeholder = 'Dirección de entrega' and @title = '.']</value>
      <webElementGuid>30f0cda6-bcd4-45ce-bf32-3dbdfcba0338</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
