<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LIMA - LIMA - VILLA MARIA DEL TRIUNFO_a0a519</name>
   <tag></tag>
   <elementGuidId>25ee3e96-42de-4d53-a3c0-559be14f6fbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_direccion_entrega_refCA']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_direccion_entrega_refCA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24196eaa-31a3-4f1c-b2ec-2e6e37e1281d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5e562653-339f-48a3-bbe4-a72b2bcff1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_direccion_entrega_refCA</value>
      <webElementGuid>9e5ebe9f-8078-4daf-83a6-9ac39413e4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_direccion_entrega_refCA</value>
      <webElementGuid>e74a3806-16d1-4094-9264-5e67c2d8b74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Referencias</value>
      <webElementGuid>4cf03240-4362-4562-9aae-5e2e02e7409b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-first-name form-control msg_alert_tt inputRE validMaxConsignado</value>
      <webElementGuid>73e4850e-d0e5-4c85-8a11-45554a9cc175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>5d0b66f9-4a01-400c-94f1-4f046b62a728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>e2b248a0-1873-4cc4-83d4-681665d5fbd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_direccion_entrega_refCA&quot;)</value>
      <webElementGuid>43e886e9-9b87-4929-a27e-a631e5f1f522</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_direccion_entrega_refCA']</value>
      <webElementGuid>fa414f96-9b73-4bbb-93f6-76111acd9242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRetornoCargo']/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>dc9e4718-0548-44eb-9a01-0e129d2e853d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>e76a1c94-24a9-4aa3-8b10-4a79b1d8057e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txt_direccion_entrega_refCA' and @id = 'txt_direccion_entrega_refCA' and @placeholder = 'Referencias' and @title = '.']</value>
      <webElementGuid>d1f46c5d-a8de-4a3a-89e6-9f9b9cf33f1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
