<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i</name>
   <tag></tag>
   <elementGuidId>e322e92d-60ab-4f14-a90d-322bd3fc636b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;paymentMethods&quot;]/div/div/section/label[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.radio.state-success > i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>05dc628b-e6e5-4fc7-ae4c-77f879f2f6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentMethods&quot;)/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col col-11&quot;]/section[1]/label[@class=&quot;radio state-success&quot;]/i[1]</value>
      <webElementGuid>3937000f-eb34-47fb-885d-69b0cffa2e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Registro de envíos/Test cases/1-Principal/iframe_Aceptar_visaNetJS</value>
      <webElementGuid>e2282892-1f17-4475-a8fd-79689eb7da36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethods']/div/div/section/label/i</value>
      <webElementGuid>e4158b83-54f6-483b-84f1-53ad1e6b42a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/section/label/i</value>
      <webElementGuid>673378f1-ebbd-4b4f-9c3f-a72e0823f359</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
