<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Aceptar_visaNetJS</name>
   <tag></tag>
   <elementGuidId>835a55e0-100d-45d8-8187-fe10dfabbb07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='visaNetJS']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#visaNetJS</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8264aad0-949f-4c17-bd94-ca05aedc4d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visaNetJS</value>
      <webElementGuid>1fe85a2d-0824-46be-94f1-c7008988b20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>577143f5-7863-4f62-bd54-db40a8964cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1cf5de7a-c1c3-4d01-ba86-4bb0bdd9f116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static-content-qas.vnforapps.com/v2/visanet.html?0.992320083286313&amp;qa=true</value>
      <webElementGuid>160b69db-1561-4a34-a209-f69e62e6f508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visaNetJS&quot;)</value>
      <webElementGuid>5d380e28-b462-47a6-82d7-d58c47025b39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='visaNetJS']</value>
      <webElementGuid>54d71d17-ec56-4783-8c83-4b5a19aea381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='visaNetWrapper']/iframe</value>
      <webElementGuid>29736af9-4818-460f-9f60-ec1df76c8eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>1568242d-7fdd-4313-8380-642252704a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'visaNetJS' and @src = 'https://static-content-qas.vnforapps.com/v2/visanet.html?0.992320083286313&amp;qa=true']</value>
      <webElementGuid>936a592a-df80-4165-9df8-ce3bea324ac5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
