<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_RegDosEnv</name>
   <tag></tag>
   <elementGuidId>368e6190-ac99-44bd-85e5-2d70b817ef56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img_caja</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img_caja']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4d73d426-9a93-4f3f-b560-66b0c946db7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_caja</value>
      <webElementGuid>e0c8ef4d-eece-4d29-b5f5-cf0f5dd9ac56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev-registrodeenvios.olvacourier.com/assets/img/compra_cajas.png</value>
      <webElementGuid>c0738f8e-bd07-4a18-8ce2-7d784086ea5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>74ee7af5-8a56-4414-9695-4af0d2c126b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>d81c31cf-6b31-40b1-b893-0e192ffe52a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>e2966517-193d-4ad6-bf06-0767fbb4d176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_caja&quot;)</value>
      <webElementGuid>89d5485a-64d1-4126-b2b7-0b971853137d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_caja']</value>
      <webElementGuid>67ecbe6a-eb39-4916-aa5e-99c5f0a4da61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figure[@id='contenedor_caja']/img</value>
      <webElementGuid>d1df3791-fc26-4ac3-b182-594d3e3ca2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENVÍOS MASIVOS'])[1]/following::img[1]</value>
      <webElementGuid>d39947d5-ea97-412c-985c-95fe91c5c313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COMPRAR EMPAQUES'])[1]/preceding::img[1]</value>
      <webElementGuid>bbe4e147-3a14-4b77-9767-4a03677d8b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev-registrodeenvios.olvacourier.com/assets/img/compra_cajas.png')]</value>
      <webElementGuid>942ce393-2c20-4121-8343-f77c48bc46aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/label/div/figure/img</value>
      <webElementGuid>9d2b867e-0278-4933-8185-659ff5ceb392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'img_caja' and @src = 'https://dev-registrodeenvios.olvacourier.com/assets/img/compra_cajas.png']</value>
      <webElementGuid>9b5d71d2-72d2-4ce8-b162-53f7638c49a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
