<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Envo de cajas o paquetescon un peso mxi_37770f</name>
   <tag></tag>
   <elementGuidId>cddce369-e303-46a0-9d66-ff384c5d8e90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img_sobre']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img_sobre</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0e0eebff-58b6-4ef9-b572-2be84a399773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_sobre</value>
      <webElementGuid>cac26fa3-b5c0-46d4-b064-c446d91458b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev02-registrodeenvios.olvacourier.com/assets/img/sobre_v3.png</value>
      <webElementGuid>3bcf73d0-4cd6-436a-a5a3-64b975ca7afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>279fb599-33a5-46da-9c91-375f1f36274b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>bf2198cb-02ac-4e62-833c-5bf02426abcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>e2211ff4-336c-4e4f-9cca-8e6dd329c62a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_sobre&quot;)</value>
      <webElementGuid>842cf0e5-b267-4079-8ef5-4a4fa2999c77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_sobre']</value>
      <webElementGuid>2670fbb9-4dee-4684-86a9-c3b110f075f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figure[@id='contenedor_sobre']/img</value>
      <webElementGuid>e1a66381-fee3-4757-a6f6-d0d3d9948c56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev02-registrodeenvios.olvacourier.com/assets/img/sobre_v3.png')]</value>
      <webElementGuid>2fb8b051-19e7-42a9-8497-36641b2f7805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/label/div/figure/img</value>
      <webElementGuid>5b93f39e-0cd4-486e-9186-aa66c45f0e51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'img_sobre' and @src = 'https://dev02-registrodeenvios.olvacourier.com/assets/img/sobre_v3.png']</value>
      <webElementGuid>12e52c24-c466-4ec0-ab2d-735060872707</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
