<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_EnvDocum</name>
   <tag></tag>
   <elementGuidId>0475d066-e5c0-45a5-8311-7b741c286abf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img_masivo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img_masivo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8b49413d-5ed1-48ae-bfc2-7975ff90e6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_masivo</value>
      <webElementGuid>1f17e981-1293-49ad-aefc-a85ad79ebb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev-registrodeenvios.olvacourier.com/assets/img/masivo_v3.png</value>
      <webElementGuid>e8193f90-3622-4580-aa7d-20b1b04e01d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>9703af0b-58d1-45e0-8fb5-008876365a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>49f41d0c-e595-490e-a347-683fdd7fdfd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>ffa5ca96-3ba7-42f8-ac32-6839d4d94b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_masivo&quot;)</value>
      <webElementGuid>b9bc5917-eb15-4931-98c8-8accb0c96c7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_masivo']</value>
      <webElementGuid>01e18636-1812-45da-bf7d-48795a4c1541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figure[@id='contenedor_masivo']/img</value>
      <webElementGuid>7b264f39-2caf-480c-b75a-22c5eb7f098e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENVIAR UN SOBRE'])[1]/following::img[1]</value>
      <webElementGuid>95b0f4b9-e948-4316-9caf-09e7f43950c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENVÍOS MASIVOS'])[1]/preceding::img[1]</value>
      <webElementGuid>74ad68e9-884a-4842-a75c-c46284526d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev-registrodeenvios.olvacourier.com/assets/img/masivo_v3.png')]</value>
      <webElementGuid>0f8293ec-50fc-4ed6-a5ec-948017da5c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/label/div/figure/img</value>
      <webElementGuid>c7bc02a6-3d54-481d-9489-6c01d92a2c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'img_masivo' and @src = 'https://dev-registrodeenvios.olvacourier.com/assets/img/masivo_v3.png']</value>
      <webElementGuid>badf5633-f65b-4a9d-807b-c4c54986d50f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
