<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ApePatDNI</name>
   <tag></tag>
   <elementGuidId>908a1b80-1cb1-4bee-adf7-4abd6b8661ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_digito_verificador']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_digito_verificador</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32e7dccb-176c-498f-af5e-a02ddb05a5ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value> text</value>
      <webElementGuid>72b9fdcc-1da6-40f8-bf53-a4c60a602565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e840d747-0691-4bbb-ae61-68a7f491ee6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_digito_verificador</value>
      <webElementGuid>2e43088d-6f24-4813-938b-dc7a9419a35a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_digito_verificador</value>
      <webElementGuid>d4a8618e-cff1-4edb-b505-62dbecbf900a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>INGRESE PRIMER APELLIDO</value>
      <webElementGuid>ea7e2bd8-9503-4ee1-97f3-7916a184c3ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_digito_verificador&quot;)</value>
      <webElementGuid>e6d3904d-4bd6-40df-b7b1-9a75f2ddd528</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_digito_verificador']</value>
      <webElementGuid>4a8a2afa-e684-41ad-8c9b-e857d7b08ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalNuevoDigitoVerificador']/div/div/div[2]/div/div[2]/input[2]</value>
      <webElementGuid>354ab398-a265-4935-913d-0845458badf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input[2]</value>
      <webElementGuid>3358222c-7fc4-456f-83ca-d2a10c35fc77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = ' text' and @id = 'txt_digito_verificador' and @name = 'txt_digito_verificador' and @placeholder = 'INGRESE PRIMER APELLIDO']</value>
      <webElementGuid>1eb3ebfc-4a0b-4391-9002-d67cfb996083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input[2]</value>
      <webElementGuid>a8c7f3c3-7463-489c-a640-63ed72df5dc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
