<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qu Envas_input_valor</name>
   <tag></tag>
   <elementGuidId>451cf5ca-b9f2-4f54-8d41-1b450a7757fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_valor']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input_valor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37d918a3-a038-4e29-8c98-8309898401f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9cbe5864-006a-468a-87b6-d4364f0a0932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>2bc0412b-421e-4f1c-ae62-2377b27f4536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>54e33d7d-4f6a-449b-988b-9d0d81ff9f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Valor S/</value>
      <webElementGuid>c541f351-1d12-4e99-b117-979fcfa97c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-first-name form-control msg_alert_tt</value>
      <webElementGuid>efebeb9a-d7ca-4ba5-bde8-5b467aa6247d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_valor</value>
      <webElementGuid>b020e293-6cec-4ae4-bc85-a42dbe07abe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_valor</value>
      <webElementGuid>3ce1dc5b-452b-47fc-b7f8-2659d875f37a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>f13c1efd-50f8-4387-becf-8ec6199ab534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>78f7e05f-273c-4c6c-bad8-d228e0bf1c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Colocar el valor real del producto, en caso de siniestro, este será el monto para los cálculos correspondientes.</value>
      <webElementGuid>31bcbe7a-3fe8-4d15-8dd7-9d2369057663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_valor&quot;)</value>
      <webElementGuid>196d9602-dadf-45d3-845e-b5b5e5dcc428</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_valor']</value>
      <webElementGuid>ca36a880-0d0a-41f8-9e14-6addbf71c17a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='que_envias_sobre']/div[2]/div[4]/input</value>
      <webElementGuid>da3bb9dd-72c4-48a2-82f2-a89467af87c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[4]/input</value>
      <webElementGuid>2ca3a15e-59f0-445d-8db2-e1c60b6aa31f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Valor S/' and @name = 'input_valor' and @id = 'input_valor' and @type = 'number']</value>
      <webElementGuid>2820d093-75d9-4b1e-ad2a-d78c992440bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
