<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qu Envas_input_descripcion</name>
   <tag></tag>
   <elementGuidId>ed1c2810-a598-4b07-8ce9-60d7928ccfc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_descripcion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input_descripcion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a680122-ca80-4d22-bfab-ca0369d67e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9991ad4c-1055-423c-9fbe-a6dae672b406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>548b01a7-e3a0-48ec-bf6f-2b6d9537e7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>21e59657-f1dc-4254-b77b-2750011ec77a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Especificar artículo</value>
      <webElementGuid>e66058ef-1cea-4ffa-b0b2-f315f149bb5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-first-name form-control msg_alert_tt inputRE</value>
      <webElementGuid>ad42ec3b-4327-4d40-89a8-20e2d68ec288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_descripcion</value>
      <webElementGuid>a4bb2e61-614f-4370-a0d4-c23e4f1458ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_descripcion</value>
      <webElementGuid>b3893c31-7f62-4d2a-a41e-6837c34ab2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_descripcion&quot;)</value>
      <webElementGuid>80fd992d-a3e4-4f51-b7c7-96c50977a309</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_descripcion']</value>
      <webElementGuid>dd972b8c-20ae-4311-898f-83c9f961cccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='que_envias_sobre']/div[2]/div[3]/input</value>
      <webElementGuid>a3f8e7fe-59b5-4b21-831a-31e124dc30d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/input</value>
      <webElementGuid>2759b0a7-7815-4110-850b-020e2503cf7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Especificar artículo' and @name = 'input_descripcion' and @id = 'input_descripcion']</value>
      <webElementGuid>a9063a5b-84a1-46bd-82e3-bc6979e1a416</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
