<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_El apellido ingresado debe ser igual _544e76</name>
   <tag></tag>
   <elementGuidId>22a1bee1-3e3b-45b5-9df3-70f06ba2a47b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_digito_verificador']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_digito_verificador</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08355c9b-c69a-4247-984d-a28c859cc228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value> text</value>
      <webElementGuid>22a2fb81-5c9d-46b9-b8b3-a8e8e449f935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>45bb0d8b-cd01-4edf-b062-9cb8a2b92d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_digito_verificador</value>
      <webElementGuid>a1d146b5-609c-4fd1-a5fb-b9703af93a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_digito_verificador</value>
      <webElementGuid>3771a42f-9019-4733-b0e3-5abee2d99291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>INGRESE PRIMER APELLIDO</value>
      <webElementGuid>812266d3-e95c-4f1b-8943-ecf8aed4d0ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_digito_verificador&quot;)</value>
      <webElementGuid>f876ace1-4ae8-4da1-b97d-af490639eafa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_digito_verificador']</value>
      <webElementGuid>9ad93f7e-f87e-4e3a-8d54-eaf6c76337f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalNuevoDigitoVerificador']/div/div/div[2]/div/div[2]/input[2]</value>
      <webElementGuid>855e5f39-956c-4b96-aa59-845b00757fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input[2]</value>
      <webElementGuid>49caff64-f8fa-4f35-b4fd-cecbd6b2c11a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = ' text' and @id = 'txt_digito_verificador' and @name = 'txt_digito_verificador' and @placeholder = 'INGRESE PRIMER APELLIDO']</value>
      <webElementGuid>8ae5f822-1d9e-4768-bdb7-7681bfabed0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
