<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_Aceptar</name>
   <tag></tag>
   <elementGuidId>cd968cc5-aec7-43e7-a286-193edabfd86a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buttonAceptarClave > h3 > center > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='buttonAceptarClave']/h3/center/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>8484e898-5e42-4759-bd2a-5e7c9d877cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>15e671df-6626-44dd-834f-8d3b703a652d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonAceptarClave&quot;)/h3[1]/center[1]/b[1]</value>
      <webElementGuid>b466c0cd-51a1-486a-b3ed-d0b6e64d2dda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buttonAceptarClave']/h3/center/b</value>
      <webElementGuid>4b8973e6-d268-4670-a247-366f4205732d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Envía la clave de seguridad a la persona que vaa recoger el envío.'])[1]/following::b[1]</value>
      <webElementGuid>5ea31b6b-0bf6-43d3-9d2d-f690b6f51fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¡IMPORTANTE!'])[1]/following::b[1]</value>
      <webElementGuid>8d27bf4e-adf1-4d03-9784-2a7f150f5b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[5]/preceding::b[1]</value>
      <webElementGuid>58511d2b-1c59-4143-bb01-5fa213a91072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tracking Web'])[1]/preceding::b[1]</value>
      <webElementGuid>fdab7124-6af5-4af0-8246-4ee7866d26c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h3/center/b</value>
      <webElementGuid>35c64a1d-e0df-42f2-aa0e-4dca36f248d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Aceptar' or . = 'Aceptar')]</value>
      <webElementGuid>edb4ac79-db89-479a-b2c9-cc23352263e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
