<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PAGAR</name>
   <tag></tag>
   <elementGuidId>72bd1541-280c-4b85-b5e5-539184cbaab0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-pagar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-pagar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a5c68faf-1fd1-48e9-b800-47cc94a03f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-pagar</value>
      <webElementGuid>1ce13f9c-5542-4f37-b93b-74db86d2b757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning btn-pagar btn-pagar-2</value>
      <webElementGuid>c71a138f-abae-4032-a208-79bff702e7c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PagarJS.preGuardarPreventa()</value>
      <webElementGuid>1cb8eacd-5852-494f-9e45-d5661cf5898c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAGAR</value>
      <webElementGuid>0373f824-ca68-4508-b8f4-e65b060c32ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-pagar&quot;)</value>
      <webElementGuid>dd7fab42-3d97-4709-a6c0-140c071e9f89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-pagar']</value>
      <webElementGuid>5db7844b-1429-4cff-9766-777ff02e2cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenedorBtnPagar']/button</value>
      <webElementGuid>b2fa7d27-ed7f-4143-a3ad-d756cce69325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALIDAR'])[1]/following::button[2]</value>
      <webElementGuid>01505789-1d1b-4de4-94f8-7866e86bbb5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/ 7.30'])[1]/following::button[3]</value>
      <webElementGuid>99abdd2d-bfec-4390-b88e-e78056c0555a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mensaje'])[1]/preceding::button[1]</value>
      <webElementGuid>05838592-a24f-4f97-bd8c-119902e8a43e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[1]/preceding::button[2]</value>
      <webElementGuid>941286dd-32bf-4f21-b5c1-6d2f6c401d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PAGAR']/parent::*</value>
      <webElementGuid>175ce79c-fe00-4504-ba72-a3eda0454b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>f446a467-fae9-4151-b67d-98b09ead153a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-pagar' and (text() = 'PAGAR' or . = 'PAGAR')]</value>
      <webElementGuid>abd21bc9-934b-41ef-9749-612648d87697</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
