<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Editar</name>
   <tag></tag>
   <elementGuidId>0d42127a-d2d9-440d-bbd4-b578d1f39de5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.button.icon-action-envio.edit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='parentNode.submit();']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2b712196-5270-4897-8be9-476b2d7a0929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button icon-action-envio edit</value>
      <webElementGuid>f8308646-c07f-4c21-91b7-502c21a01feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>parentNode.submit();</value>
      <webElementGuid>ce17036f-17df-440c-88ca-4cfb6928d974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Editar</value>
      <webElementGuid>097c17b4-7583-459d-80eb-e89d3133b675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blueTable_wrapper&quot;)/table[@id=&quot;blueTable&quot;]/tbody[1]/tr[@class=&quot;odd&quot;]/td[1]/form[@class=&quot;btn-edit-acciones&quot;]/button[@class=&quot;btn button icon-action-envio edit&quot;]</value>
      <webElementGuid>4e4e9667-1bc9-487c-ab8c-a50c94d6845e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='parentNode.submit();']</value>
      <webElementGuid>eb3844f7-4313-4057-bfde-b24257be16f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='blueTable']/tbody/tr/td/form/button</value>
      <webElementGuid>58c4eb0a-c757-4a9c-b178-86e094a757e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/ 8.30'])[1]/following::button[1]</value>
      <webElementGuid>627bd95c-570d-4800-8079-61fbdabe4d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/ 0.00'])[1]/following::button[1]</value>
      <webElementGuid>4bd85f49-c6d3-4e49-be26-2f3a30ac7285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar'])[1]/preceding::button[1]</value>
      <webElementGuid>3199e143-b531-4393-9f0a-b95726db4516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anterior'])[1]/preceding::button[2]</value>
      <webElementGuid>573b07e8-3faf-4c49-80c7-9fbf3b9dbc06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Editar']/parent::*</value>
      <webElementGuid>dddcb0b6-3a2c-4734-bc82-8a3302499748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>c7a149ec-81a4-4d6a-bb07-d8f2196994a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Editar' or . = 'Editar')]</value>
      <webElementGuid>e101fc33-f59d-44d6-9fbd-73ec467567ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
