<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tracking Web_sa-icon sa-custom</name>
   <tag></tag>
   <elementGuidId>0addca3f-052f-47af-a570-6a11bd9093f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sa-icon.sa-custom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[5]/div[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>63dfe02f-0ea1-4e84-8e5e-93c48b92869c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sa-icon sa-custom</value>
      <webElementGuid>7bb5f3f0-1f4e-4d5e-8aec-9fe7754777c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;stop-scrolling&quot;]/div[@class=&quot;sweet-alert showSweetAlert visible&quot;]/div[@class=&quot;sa-icon sa-custom&quot;]</value>
      <webElementGuid>b6e13ac1-2e4b-462e-8a8f-aa20755ad591</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[5]</value>
      <webElementGuid>34aea41b-c396-4fbb-82b5-ea7237229fd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
