<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OLVA</name>
   <tag></tag>
   <elementGuidId>8a909ed0-5b9c-47fc-b178-cafeca6ca613</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#div_ape_pat_dif</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div_ape_pat_dif']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6376e482-e5d7-444a-8814-ac2648923a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>div_ape_pat_dif</value>
      <webElementGuid>e49deb6e-7cdd-4d86-abd6-71cc3036d4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-first-name form-control msg_alert_tt inputRE validMaxConsignado</value>
      <webElementGuid>3f38e26d-edb1-4ccd-9cee-cf39ad250276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>div_ape_pat_dif</value>
      <webElementGuid>7c4ca862-94ac-4bba-a9d2-5c3d0e687bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OLVA </value>
      <webElementGuid>8dca2459-aab5-4ee1-87f9-aea411152ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_ape_pat_dif&quot;)</value>
      <webElementGuid>84cb7f1c-a0de-4fb7-ac50-c3afa3e629ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='div_ape_pat_dif']</value>
      <webElementGuid>020a164a-930a-426e-b4e1-1a5582fceb4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_consignado_ape_pat_dif']/div</value>
      <webElementGuid>6742fa0c-e38e-462c-91a1-b9e492263d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARNÉ EXT.'])[3]/following::div[18]</value>
      <webElementGuid>d7e9c2b1-18a4-411e-8388-95d8248c01bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RUC'])[2]/following::div[18]</value>
      <webElementGuid>bfb5c45b-5219-49a9-8438-b428734c00b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUAR'])[1]/preceding::div[3]</value>
      <webElementGuid>cb2ecce8-f46a-462d-9985-b9a482fe251b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[5]/div[4]/div</value>
      <webElementGuid>9b6eb9a2-8d07-404f-aeec-44bfd04dd5c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@name = 'div_ape_pat_dif' and @id = 'div_ape_pat_dif' and (text() = 'OLVA ' or . = 'OLVA ')]</value>
      <webElementGuid>01311441-3683-4ec8-9ec5-a3f70d971d44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
