<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OLVA_txt_consignado_ape_mat</name>
   <tag></tag>
   <elementGuidId>7fb6ca46-de63-4954-aad9-62cdff7a741b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_consignado_ape_mat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_consignado_ape_mat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c97760f-1fbf-4f14-8a63-37b1167abf3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>97b21480-dcc9-406f-bac4-ff316cc1a2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>14c93156-fa2e-4e86-b07d-03f71e6cd4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_consignado_ape_mat</value>
      <webElementGuid>91be0415-3022-4f8e-afd9-57f0e4762bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>c7491ee1-454a-4dbc-abaa-2068ee261511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Apellido Materno</value>
      <webElementGuid>0a7e1741-8355-4bbc-8fbf-1fe0598a3b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-first-name form-control msg_alert_tt inputRE validMaxConsignado</value>
      <webElementGuid>12437b6a-77d5-4dbc-aeea-b5d757b16fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_consignado_ape_mat</value>
      <webElementGuid>0c8a3725-d734-4c97-8106-99b11f70b871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>c2cfbf2e-5275-428b-aee9-3fcc3dd8bbb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>VASQUEZ PROB</value>
      <webElementGuid>06a66e65-c4d7-45cf-ad66-66f169ffe28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_consignado_ape_mat&quot;)</value>
      <webElementGuid>5b0ce3ba-fe12-4144-86fa-d29e88d1a25f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_consignado_ape_mat']</value>
      <webElementGuid>e433fa1c-76c9-477c-96d2-98c416b9f9d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_dni_ce']/div[5]/input</value>
      <webElementGuid>550eb0d5-f8cc-4526-937d-615fca21218c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[5]/input</value>
      <webElementGuid>df7ffdbc-6a02-4dd1-93ac-ad91c5c4d383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txt_consignado_ape_mat' and @placeholder = 'Apellido Materno' and @id = 'txt_consignado_ape_mat' and @title = '.']</value>
      <webElementGuid>40054ca2-0fc1-41b6-8006-8d92dd7510d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
