<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tienes envos con recojo en tienda, se_653975</name>
   <tag></tag>
   <elementGuidId>be1c24d4-1322-4930-aa2d-83cbb1aaad5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#digito3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='digito3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22df1c8c-7252-48cb-919d-c40bcbc1e77c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>digito3</value>
      <webElementGuid>43d2300b-1fb0-4474-b47b-4054b2669c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>65d4e383-5b51-4004-9e49-1091aaf8474c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>3ee5c4bf-b4c8-4e22-8569-81e81f75699f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f955f165-dc57-4c87-a12c-5b2d34e8ebf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return digitKeyOnly(event)</value>
      <webElementGuid>713d50e6-d58c-4a64-83c7-176939a90b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);</value>
      <webElementGuid>508f51b6-ea3f-413e-8e5b-10b46d00ba43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;digito3&quot;)</value>
      <webElementGuid>12210a20-f93d-45fc-8f40-fd339baa8401</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='digito3']</value>
      <webElementGuid>934d3890-3aa9-4d33-ae10-096818f5ca31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myModalClaveSeguridad']/div/div/form/div/div/div[3]/input</value>
      <webElementGuid>153f6b12-95ca-4051-a90d-004ef4b7445a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[3]/input</value>
      <webElementGuid>0e1217e3-91fc-4dd3-a587-6f19e3cc33c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'digito3' and @type = 'number']</value>
      <webElementGuid>0d133d64-e434-4dd8-99c3-feebd0b127b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
