<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_El apellido ingresado debe ser igual _544e76</name>
   <tag></tag>
   <elementGuidId>782aad9c-6b16-4909-b878-7da29bb49e72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_digito_verificador</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_digito_verificador']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d127984f-5129-4dcd-9ae9-346ad13c16df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value> text</value>
      <webElementGuid>e1fb5cf7-35e6-44c4-afa8-f5e9a6a8881f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a91ff806-a328-49f0-a2b3-0ab6847ac202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_digito_verificador</value>
      <webElementGuid>1b17af27-081f-45e5-9121-406cc15b64aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_digito_verificador</value>
      <webElementGuid>36f7b0ea-f244-4cdd-bc7a-abf4566b599a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>INGRESE PRIMER APELLIDO</value>
      <webElementGuid>be90474f-57f0-4bf4-aa36-baed199482d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_digito_verificador&quot;)</value>
      <webElementGuid>8d754fea-8cfb-4322-8177-4ecedf6202d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_digito_verificador']</value>
      <webElementGuid>6ecf1f5e-dff8-40de-afb7-0b8a5d6d9d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalNuevoDigitoVerificador']/div/div/div[2]/div/div[2]/input[2]</value>
      <webElementGuid>9865b17d-febc-4d46-8ae7-70ab5add49ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input[2]</value>
      <webElementGuid>2c7ad0fc-b64d-4f0d-a3af-4dec8135a6b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = ' text' and @id = 'txt_digito_verificador' and @name = 'txt_digito_verificador' and @placeholder = 'INGRESE PRIMER APELLIDO']</value>
      <webElementGuid>7aa91fc1-4f67-4ca6-9e5c-f0d2900e62c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
