<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CARN EXT. (Boleta)_txt_documento_cliente</name>
   <tag></tag>
   <elementGuidId>5a51f094-6f06-4f03-8469-171ef1b33051</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_documento_cliente</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_documento_cliente']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>595bb5e6-e00d-48ed-ad0b-f08a6de69b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>db4caa0f-8b04-48a7-893c-3d3cf5956bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6aa98e04-ff54-4209-9133-a20f526c1143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validateDNI()</value>
      <webElementGuid>6baddb3c-2476-4c43-8d1b-891ef71ccf2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_documento_cliente</value>
      <webElementGuid>02b9677a-17ec-41a0-b171-1d110b6afed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>15278d39-3599-4425-9859-56c03cd5199b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Número</value>
      <webElementGuid>a908402e-e70e-4526-88cd-b64b48c3663e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control msg_alert_tt</value>
      <webElementGuid>10cbc475-a6f5-4365-862f-cafb3f39df92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>21f3f97e-7531-4fea-83ed-e050c3135e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_documento_cliente</value>
      <webElementGuid>7bf1cc15-7a55-4fd5-9fd7-76bf70439b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return nuevoEnvioJS.validateNumber(event);</value>
      <webElementGuid>8d54960b-467e-4fd1-ba2f-0d9a3d3c2738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>438b0282-7b86-4eae-8c10-de3296bacbca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_documento_cliente&quot;)</value>
      <webElementGuid>304207d0-8658-4d3e-97a0-d12a92fb36aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_documento_cliente']</value>
      <webElementGuid>3a6409bd-d2be-4466-a988-106af2e9df72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quien_envia']/div[2]/div[4]/input</value>
      <webElementGuid>7f5797e4-0b4e-4e20-bed1-5ccbe2a12f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>a600fd7d-f777-471b-bfd4-94a30e384c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txt_documento_cliente' and @placeholder = 'Número' and @title = '.' and @id = 'txt_documento_cliente']</value>
      <webElementGuid>e4431431-b637-47fb-808f-1ac47f962560</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
