<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UTILES DE OFICINA_txt_paquete_articulo</name>
   <tag></tag>
   <elementGuidId>51696c91-ac92-41c5-9eda-957ec2755628</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_paquete_articulo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_paquete_articulo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e21bd33-5e26-4981-afc9-858f32074d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9ffd0808-e4d1-4cbf-b9ac-efb25aa533e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>811afc5d-882c-46ba-8f41-e903c0199bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>43abee6f-4738-4a48-b28d-78d858c961d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Especificar artículo</value>
      <webElementGuid>bb88c415-d371-4a5a-8506-5dc7adf170cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-first-name form-control msg_alert_tt inputRE</value>
      <webElementGuid>0df9c3ae-dd5a-441c-99b9-549bd0261de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_paquete_articulo</value>
      <webElementGuid>520d5d8e-d4f5-4d6f-94d3-1d1d341c0a5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_paquete_articulo</value>
      <webElementGuid>75f6006e-42e1-4aa7-a9ef-b904b0cc8ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_paquete_articulo&quot;)</value>
      <webElementGuid>5b50eec1-b89d-44a9-a70f-98aaf425f7fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_paquete_articulo']</value>
      <webElementGuid>9e018929-64ec-456f-a85b-fd8760d0ea54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_articulo_descripcion']/input</value>
      <webElementGuid>aa5b39b1-f891-4a21-93f5-de7e36fe621e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[3]/input</value>
      <webElementGuid>87d10575-798b-4e40-94b0-985091a0117a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Especificar artículo' and @id = 'txt_paquete_articulo' and @name = 'txt_paquete_articulo']</value>
      <webElementGuid>99a4204d-cd52-47e6-88fb-872062584e0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
