<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dnde lo entregamos_txt_direccion_entrega</name>
   <tag></tag>
   <elementGuidId>9bfa52c9-d80a-46e2-b074-c7b936f09a35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_direccion_entrega</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_direccion_entrega']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82eb6d8b-afa5-47bd-9b86-fcac6d75fc13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>795248e9-2823-46b9-8871-b40a11dbf4f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>13ec9567-e70d-4d5d-a803-5d57b0db9c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_direccion_entrega</value>
      <webElementGuid>c6769dfe-8bb3-4a1a-ba34-3c6d182c1838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Dirección de entrega</value>
      <webElementGuid>756458d1-ea71-4049-a830-58d090c3abfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-first-name form-control msg_alert_tt inputRE validMaxConsignado icon</value>
      <webElementGuid>d1dcc4c6-674c-43f1-8104-e09a630c45c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>ee95a601-219e-4b42-9dbc-2625180254e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_direccion_entrega</value>
      <webElementGuid>33e491e2-fcfe-457b-a4b5-29ae9b33a6cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>8fee34c2-89e9-4d93-9a79-eabcf1786061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_direccion_entrega&quot;)</value>
      <webElementGuid>ece60434-0365-4fbc-9540-efcc21f60d15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_direccion_entrega']</value>
      <webElementGuid>cdb00091-0748-46eb-b3e4-aab0495c68a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldset_paso1']/div[7]/div[2]/div[2]/div/input</value>
      <webElementGuid>c36f4344-3f8d-44ef-adbe-0776fdcf34ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div[2]/div/input</value>
      <webElementGuid>7669c7b5-b70e-4964-83d0-075586f447c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txt_direccion_entrega' and @placeholder = 'Dirección de entrega' and @id = 'txt_direccion_entrega' and @title = '.']</value>
      <webElementGuid>1d9e79d6-2f7b-4d8f-b48a-8f18d5bfed1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
