<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_He ledo y acepto los_checkmark</name>
   <tag></tag>
   <elementGuidId>0f92c9b1-50f2-4ffd-901d-ce44bd4178b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.checkmark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form_tipo_envio']/p/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f4134f2b-08ba-441b-8938-a84cdfa35d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>30ee62f0-da56-44b7-b3ae-7c0d8bb8dbe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_tipo_envio&quot;)/p[@class=&quot;terms&quot;]/label[@class=&quot;container-check&quot;]/span[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>cc52d50d-97ed-4ef1-b246-fa409f671601</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_tipo_envio']/p/label/span</value>
      <webElementGuid>ccb6e13c-9144-4cd0-847a-98ef7360ab06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>f05d5ee2-9cd4-4067-abff-6a70ea08b2f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
