<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_202407711343</name>
   <tag></tag>
   <elementGuidId>d309fcc8-d4dc-4af7-a6e1-a2fb691d6591</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//b[@id='nroPedido3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nroPedido3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>49d742ec-562e-455e-ac87-f378cfa6293f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nroPedido3</value>
      <webElementGuid>cb7ab35b-4092-4668-872f-8f6d0ef4e36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nroPedido3</value>
      <webElementGuid>0d11c0a3-2f58-4ced-968d-99bd1c7a5e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>202407711343</value>
      <webElementGuid>a2d8d9b9-7b74-42db-b711-59262cf0c2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nroPedido3&quot;)</value>
      <webElementGuid>53e19a61-f8bd-4dde-9103-edf0de26355b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//b[@id='nroPedido3']</value>
      <webElementGuid>acc75521-6b46-4627-9dc8-e002f46effb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/fieldset/div[2]/div[2]/b</value>
      <webElementGuid>a73e8d0f-798e-43fd-8fc9-8131280ecbd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Se envió un correo con los detalles de su registro.'])[1]/following::b[1]</value>
      <webElementGuid>e6844d42-14be-4be8-99b9-7a564bd5ab27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUAR'])[1]/preceding::b[1]</value>
      <webElementGuid>43b769a3-539f-4a78-ae0b-673c796e3830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tracking Web'])[1]/preceding::b[1]</value>
      <webElementGuid>554d387b-1fcd-4796-b6d9-f04dd85885dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='202407711343']/parent::*</value>
      <webElementGuid>a0fa51c1-f893-4c78-8741-7046dfe417fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>da3e2671-76b5-4e5d-9825-cb5412521e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[@id = 'nroPedido3' and @name = 'nroPedido3' and (text() = '202407711343' or . = '202407711343')]</value>
      <webElementGuid>5b6f2a4a-2c35-49d5-8feb-901150da0742</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
