<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PINTO</name>
   <tag></tag>
   <elementGuidId>d28028ae-3927-4655-b21e-0340d2c9a36a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div_ape_pat_dif']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#div_ape_pat_dif</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d4d4cd90-870d-4431-99c2-0a7db5adacdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>div_ape_pat_dif</value>
      <webElementGuid>fc964551-b685-4335-b532-aca20800d47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-first-name form-control msg_alert_tt inputRE validMaxConsignado</value>
      <webElementGuid>914b2b21-3958-490e-8c3f-dbfe295e052b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>div_ape_pat_dif</value>
      <webElementGuid>68c9dbf8-9eb6-4288-a877-d0722ad55308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> PINTO  </value>
      <webElementGuid>4645805a-0cf9-4ceb-8a71-25390c47e983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_ape_pat_dif&quot;)</value>
      <webElementGuid>181c81d2-2d2f-4b40-ac85-e93d17840d50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='div_ape_pat_dif']</value>
      <webElementGuid>1dd3d64d-6f67-4e14-b3c5-49838a6382c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_consignado_ape_pat_dif']/div</value>
      <webElementGuid>69007b1b-2f5d-4a30-a02a-9bb218b9ae81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARNÉ EXT.'])[2]/following::div[18]</value>
      <webElementGuid>688f9923-b429-4fb4-86a0-1b66d89f8e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RUC'])[2]/following::div[18]</value>
      <webElementGuid>363314f1-2d8e-4dd5-9edc-8006d9d3acc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUAR'])[1]/preceding::div[3]</value>
      <webElementGuid>19206a26-bcbb-4344-9560-985a7dc357cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[4]/div</value>
      <webElementGuid>a2895068-1d6b-46f4-8233-301657cde282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@name = 'div_ape_pat_dif' and @id = 'div_ape_pat_dif' and (text() = ' PINTO  ' or . = ' PINTO  ')]</value>
      <webElementGuid>6d30ced8-2d68-4890-b157-bccdc4f8b8be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
