<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_paquete</name>
   <tag></tag>
   <elementGuidId>57de3663-308c-4d50-a1bc-736ba2a3ed0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img_paquete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img_paquete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b8bfe369-3600-4fa8-83dd-9ed5af79be9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_paquete</value>
      <webElementGuid>46e1894c-ffe1-40c9-8417-fe279e41b01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev-registrodeenvios.olvacourier.com/assets/img/paquete_v3.png</value>
      <webElementGuid>f0a2c384-d185-42af-a779-f8f5ef71d19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>1cd915cc-7532-4699-9894-5446c64b3f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>8910ff46-474b-4f21-8fcb-dc3f504ad5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>7e0c06a6-24ed-463b-b20e-24e41b566baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_paquete&quot;)</value>
      <webElementGuid>f0f8bfd4-0e21-4a9b-a3c3-beb496122db9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_paquete']</value>
      <webElementGuid>0703b550-e2fb-4176-8b07-b2a95f2ce59f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figure[@id='contenedor_paquete']/img</value>
      <webElementGuid>3d64f38a-b71d-40e0-a525-fc446f27d1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Qué deseas realizar hoy?'])[1]/following::img[1]</value>
      <webElementGuid>c2efc085-1ed0-4891-af53-53d425f93f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regresar'])[1]/following::img[1]</value>
      <webElementGuid>7de42528-5f95-439a-8945-81dab18441bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENVIAR UN PAQUETE'])[1]/preceding::img[1]</value>
      <webElementGuid>b64752e1-1e37-4b92-9e7e-b6799459aa3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev-registrodeenvios.olvacourier.com/assets/img/paquete_v3.png')]</value>
      <webElementGuid>c4954cb8-cb09-4390-b999-53568156b8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/img</value>
      <webElementGuid>db530397-7380-43ed-93b6-9f9ec60c9cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'img_paquete' and @src = 'https://dev-registrodeenvios.olvacourier.com/assets/img/paquete_v3.png']</value>
      <webElementGuid>9dd8bd60-5d10-45fc-bb35-ee474aaab2dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
