<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_dir_entreg</name>
   <tag></tag>
   <elementGuidId>55df1472-dc3b-4e2e-bb0a-7b2e47e0a33f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_direccion_entrega']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txt_direccion_entrega</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8411c2b7-776b-4edc-8464-8ca0e0ca70d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6de141f4-c2fc-40e7-9394-6a022789ca58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e1152629-f576-4c7b-8b68-2609a868d0fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_direccion_entrega</value>
      <webElementGuid>03ec5702-5bb7-4a60-a9b4-39c90b8601eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Dirección de entrega</value>
      <webElementGuid>6691766b-f062-4c8f-a274-88941e8ea14b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-first-name form-control msg_alert_tt inputRE validMaxConsignado icon</value>
      <webElementGuid>dc847cd0-de43-42de-9009-24789ddc21eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>0d030eaf-ea03-460d-af5b-7157b195ba8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_direccion_entrega</value>
      <webElementGuid>931b5a6e-e276-4f6a-8716-8af0adf80c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>2c736962-c461-4959-bafa-ef0fe49ccc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_direccion_entrega&quot;)</value>
      <webElementGuid>e865eedb-fd2f-4e8e-ba7e-3db31acb3bc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_direccion_entrega']</value>
      <webElementGuid>fe3e6c3a-5cd9-438e-a8a0-27338ad25265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='fieldset_paso1']/div[7]/div[2]/div[2]/div/input</value>
      <webElementGuid>541db2e9-cfc7-4dd8-a0b8-c39782b7db80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div[2]/div/input</value>
      <webElementGuid>b4e561ea-0aa8-4e21-87c9-1278e79d4ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txt_direccion_entrega' and @placeholder = 'Dirección de entrega' and @id = 'txt_direccion_entrega' and @title = '.']</value>
      <webElementGuid>c3ce8041-a6c5-4203-b332-f836cb634c76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
