<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Consig_dni</name>
   <tag></tag>
   <elementGuidId>53809287-b7fb-4137-9abb-86e658c3762a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txt_consignado_dni</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txt_consignado_dni']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eeb813b0-5049-47f0-9bf1-72e9beabe9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>df1f0a81-468b-4973-85d7-4654aaf285c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>01749b11-08ef-41ac-b67f-f92a73999685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txt_consignado_dni</value>
      <webElementGuid>587698a9-81b5-48de-8633-673b41022908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DNI/RUC/CE</value>
      <webElementGuid>820b0aee-56f7-4842-b80e-f4195c2966f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f1-last-name form-control msg_alert_tt inputRE</value>
      <webElementGuid>a104e23a-e1e6-4cf7-9333-ff27e62e06ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>7881efbb-f60d-4c6e-8d2b-498e1be6a1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txt_consignado_dni</value>
      <webElementGuid>cda68cc7-906d-4373-9db3-1e6ace88e5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>ad3f7b83-7b6a-49e4-93f7-84e79866b5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txt_consignado_dni&quot;)</value>
      <webElementGuid>496c9432-2eba-44a2-a772-93e994832085</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txt_consignado_dni']</value>
      <webElementGuid>b9b566c9-b206-4a67-ba03-2738325f5d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='quien_recibe']/div[2]/div[3]/input</value>
      <webElementGuid>d575f3c3-9fb2-435f-a968-55018cb0639a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div[3]/input</value>
      <webElementGuid>d2f9de08-8b0e-43a9-a4a4-588f2490b708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txt_consignado_dni' and @placeholder = 'DNI/RUC/CE' and @id = 'txt_consignado_dni' and @title = '.']</value>
      <webElementGuid>083644c5-d416-4304-a3af-370d73aa1ecd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
