<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_TermsyCond</name>
   <tag></tag>
   <elementGuidId>fcffe9ac-4eb9-43de-babb-66b8a882f272</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.checkmark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form_tipo_envio']/p/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ea41876d-ee81-4f4b-8fe4-42784fefe716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkmark</value>
      <webElementGuid>4b73a4b2-1dfc-4e09-8d4d-400467d98cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_tipo_envio&quot;)/p[@class=&quot;terms&quot;]/label[@class=&quot;container-check&quot;]/span[@class=&quot;checkmark&quot;]</value>
      <webElementGuid>bf936ac3-a9a2-4b3e-aaeb-58c05f660861</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_tipo_envio']/p/label/span</value>
      <webElementGuid>e6307207-f85b-43d3-82c6-358e27614968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUAR'])[1]/preceding::span[1]</value>
      <webElementGuid>519d1481-8ce5-4b22-903e-de224a9afe48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>8e3a8745-8715-4f87-bdae-56e49ef562c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
