<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ART_LIMP</name>
   <tag></tag>
   <elementGuidId>7bfb155b-fbe1-4519-9ed2-c5d509d6adac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div_articulo']/div/div/ul/li[4]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0efb9fca-a3c3-4b27-99ff-61b2facc1bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b81b558f-3859-4138-8789-d7e5fe8f0f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            ARTÍCULOS DE LIMPIEZA</value>
      <webElementGuid>265d67aa-4ad8-483d-850a-c4ed6d66435c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_articulo&quot;)/div[@class=&quot;btn-group bootstrap-select form-control msg_alert_tt dropup open&quot;]/div[@class=&quot;dropdown-menu open&quot;]/ul[@class=&quot;dropdown-menu inner selectpicker&quot;]/li[4]/a[1]/span[@class=&quot;text&quot;]</value>
      <webElementGuid>232c287c-2431-40c3-84f1-73ddd7479ebb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_articulo']/div/div/ul/li[4]/a/span</value>
      <webElementGuid>9a86db04-b025-45c1-a1b4-05f624cf0225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACCESORIOS PARA FIESTAS'])[2]/following::span[2]</value>
      <webElementGuid>b3d5d888-1cdf-4b2c-8479-8c0cf4e1a559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACCESORIOS Y EQUIPOS ELECTRONICOS'])[2]/following::span[4]</value>
      <webElementGuid>95a0c8d2-8d37-4fe3-8693-d49b5a7e3733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARTÍCULOS PUBLICITARIOS'])[2]/preceding::span[2]</value>
      <webElementGuid>e09297aa-2eed-45a8-8cf4-fa95158dea18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BISUTERIA'])[2]/preceding::span[4]</value>
      <webElementGuid>7a3c7144-6998-40e2-b1a1-31d32a5942ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/div/div/ul/li[4]/a/span</value>
      <webElementGuid>cdb436b3-1ad9-40cc-a6c8-631cbeb36e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
                            ARTÍCULOS DE LIMPIEZA' or . = '
                            ARTÍCULOS DE LIMPIEZA')]</value>
      <webElementGuid>75ac8ca2-e77d-4d17-ab15-a26c4d8d8de0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
