<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Eliminar</name>
   <tag></tag>
   <elementGuidId>ef803b5d-c9f2-45fa-a6b6-0f3121fd54ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='blueTable']/tbody/tr[5]/td/button/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6f82f012-8161-4e45-beb2-49b24a95c1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dev02-registrodeenvios.olvacourier.com/eliminar-envio/Lq803yUrFt243Rb</value>
      <webElementGuid>3fe5165f-3c9b-4603-afb3-da95609c3edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Eliminar</value>
      <webElementGuid>2d157801-2c9f-488b-875b-48603e0f086c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blueTable_wrapper&quot;)/table[@id=&quot;blueTable&quot;]/tbody[1]/tr[@class=&quot;odd&quot;]/td[1]/button[@class=&quot;btn button icon-action-envio delete&quot;]/a[1]</value>
      <webElementGuid>f1759f1c-8b8c-48d0-9175-70aadc6821f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='blueTable']/tbody/tr[5]/td/button/a</value>
      <webElementGuid>55444704-71c8-4ecc-8fa7-83676df4ab3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Eliminar')])[5]</value>
      <webElementGuid>f24e0dfa-9a78-4cca-8e32-e145bdf76267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar'])[5]/following::a[1]</value>
      <webElementGuid>886cb1b1-e6e6-40b2-954a-9ae5059b8d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/ 267.58'])[1]/following::a[1]</value>
      <webElementGuid>8da05db6-0d48-4324-a761-320254664a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anterior'])[1]/preceding::a[1]</value>
      <webElementGuid>7b59d1e3-764f-4152-a8ed-cf7fd1729fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Siguiente'])[1]/preceding::a[3]</value>
      <webElementGuid>792ad859-3368-440c-b8de-614446dfb82c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://dev02-registrodeenvios.olvacourier.com/eliminar-envio/Lq803yUrFt243Rb')]</value>
      <webElementGuid>edfb752c-4e98-4b8d-9715-6994131a49dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/button/a</value>
      <webElementGuid>67c1bd66-2994-46b8-bb43-4a2323a6894b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://dev02-registrodeenvios.olvacourier.com/eliminar-envio/Lq803yUrFt243Rb' and (text() = 'Eliminar' or . = 'Eliminar')]</value>
      <webElementGuid>a9b1b584-1a94-4099-ac32-30978e1f036e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
