<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_IR A PAGAR S 22.80</name>
   <tag></tag>
   <elementGuidId>330e2fd4-5ffe-4692-81f3-e8e2aee66236</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-pagar-listar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-pagar-listar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4c3fd491-41ca-4851-9196-e14e24059699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-pagar-listar</value>
      <webElementGuid>04fcf15f-c0df-4cfb-a9ad-7a5f65b5d713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>22.80</value>
      <webElementGuid>9effa136-620a-484d-a995-cd8ade87cf9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>87b042e5-89bd-4df8-93e8-e73d7fde7740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning</value>
      <webElementGuid>c635c030-52e9-4148-be09-439d67e06a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IR A PAGAR S/ 22.80</value>
      <webElementGuid>8ac736a6-a097-4fba-957d-776625e876a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-pagar-listar&quot;)</value>
      <webElementGuid>19b77449-28bc-4870-a3ac-0b96e941c622</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-pagar-listar']</value>
      <webElementGuid>96233131-9965-4fb3-a70a-3475f5e38123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_pagar']/button</value>
      <webElementGuid>23be0f86-7d2e-4fcf-8d2b-77ebbf4e1976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Siguiente'])[1]/following::button[1]</value>
      <webElementGuid>da5d304e-1b8d-4e54-93a8-eab9911795d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anterior'])[1]/following::button[1]</value>
      <webElementGuid>307e5997-7f60-4062-8fa9-c8d0ee899c71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿A dónde retornamos el cargo adjunto ?'])[1]/preceding::button[2]</value>
      <webElementGuid>336e7eaf-6295-48b7-a551-7ee6c4928639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de entrega'])[3]/preceding::button[2]</value>
      <webElementGuid>08142a02-862d-40f1-a7e5-2da633736ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='IR A PAGAR S/ 22.80']/parent::*</value>
      <webElementGuid>83d477dc-33ef-434d-85dd-15fe56cc9686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>57b3f54f-e91e-49e1-bf21-5b2eeb59d901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-pagar-listar' and @type = 'button' and (text() = 'IR A PAGAR S/ 22.80' or . = 'IR A PAGAR S/ 22.80')]</value>
      <webElementGuid>d140de12-b916-49a9-9aac-020f285cf0df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
