<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Envo de documentoscon un peso mximo de__78caaf</name>
   <tag></tag>
   <elementGuidId>012027ee-5bfd-468d-bfee-ba80821628eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cont_rbt_masivo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cont_rbt_masivo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>425210e9-475f-43a4-b25e-d6f3885df9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card</value>
      <webElementGuid>087a1b00-8909-4fe4-b084-ee805ae3ffe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cont_rbt_masivo</value>
      <webElementGuid>f5db6e55-ad09-44ed-9f8e-f1f9dc72aac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cont_rbt_masivo&quot;)</value>
      <webElementGuid>60e7661d-86d9-499c-b42b-dc8f0e1fb2f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cont_rbt_masivo']</value>
      <webElementGuid>1be91329-c24b-49f2-ae12-e36327ee8cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_tipo_envio']/div/ul/li[3]/label/div</value>
      <webElementGuid>47bcbfea-889e-4552-8e1d-21b4a7adf055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENVIAR UN SOBRE'])[1]/following::div[1]</value>
      <webElementGuid>2a482e52-a9a0-41f3-aced-a61cc5d7a92b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENVÍOS MASIVOS'])[1]/preceding::div[1]</value>
      <webElementGuid>6925fe34-cad1-48dc-81ec-2f4a6fed9d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/label/div</value>
      <webElementGuid>4d10edcc-c680-4268-9412-bff424d55bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cont_rbt_masivo']</value>
      <webElementGuid>9efe8537-2cb9-475f-a0c2-a305eeca9e2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
