<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Qu deseas realizar hoy_img_paquete</name>
   <tag></tag>
   <elementGuidId>3f035cc4-d50a-4d89-99f2-dece64ae58c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img_paquete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img_paquete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9f3b3e0d-266e-4034-a0e2-8f148b84916e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_paquete</value>
      <webElementGuid>de82f02c-fdb0-4558-89a2-ea66086ee1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev02-registrodeenvios.olvacourier.com/assets/img/paquete_v3.png</value>
      <webElementGuid>18b2a6b9-518d-4056-b941-841f390e8b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>0e791c2e-e49b-41b5-bd63-10e9ed607550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>53e62f93-4c9b-4afb-977c-0b2fe14f0aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>27a02174-fc32-4bf3-b226-fceaae692ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_paquete&quot;)</value>
      <webElementGuid>69212688-fbfd-41da-bd81-1bffe4edec61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_paquete']</value>
      <webElementGuid>efc74cad-ae44-4af1-9e18-939f35a25a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figure[@id='contenedor_paquete']/img</value>
      <webElementGuid>144c0978-942d-43f0-a127-74e9f4e05676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev02-registrodeenvios.olvacourier.com/assets/img/paquete_v3.png')]</value>
      <webElementGuid>a61dc433-1831-41d8-bce1-ed28b69efa83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//figure/img</value>
      <webElementGuid>53b8e061-3d8e-4028-9bed-f4ce43867116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'img_paquete' and @src = 'https://dev02-registrodeenvios.olvacourier.com/assets/img/paquete_v3.png']</value>
      <webElementGuid>eef42da7-44e7-4cd1-a7e6-20b6a1cd466c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
