<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Declaro bajo juramento los productos _f4619d</name>
   <tag></tag>
   <elementGuidId>595bad63-2676-4d0c-b336-f1525b0e7a87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='op_juramento']/ul/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#op_juramento > ul.buttons > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>412cf2bd-6a87-4758-ad15-9ecc502584b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>chk_juramento</value>
      <webElementGuid>bd77b091-eeac-4cc1-9f76-9184777b44e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Declaro bajo juramento los productos escritos en el registro de envíos. </value>
      <webElementGuid>7bcaf538-02ae-4170-9767-6e3832025f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;op_juramento&quot;)/ul[@class=&quot;buttons&quot;]/label[1]</value>
      <webElementGuid>f996c976-aec0-48f8-b78e-9f7464e93daf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='op_juramento']/ul/label</value>
      <webElementGuid>04db6238-b4c9-4238-aa5e-a858e328e920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='He leído la'])[1]/following::label[1]</value>
      <webElementGuid>a035d2e0-9652-4628-981c-506721d5e0b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/ 1234.00'])[2]/following::label[2]</value>
      <webElementGuid>12c8ac89-8e90-4fc7-b7a2-54fd6a45cdd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUAR'])[1]/preceding::label[1]</value>
      <webElementGuid>118f95e9-c905-4d8c-9fe3-296117914030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DECLARACIÓN JURADA DE CONTENIDO Y EMBALAJE'])[1]/preceding::label[1]</value>
      <webElementGuid>8b93800d-5097-4a8f-ba19-820dd14592dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Declaro bajo juramento los productos escritos en el registro de envíos.']/parent::*</value>
      <webElementGuid>a5d5d1f3-9f75-4a7d-a3e4-cf84a9478893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/ul/label</value>
      <webElementGuid>29ba46ff-7f13-422c-ab2a-d1fa38936d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' Declaro bajo juramento los productos escritos en el registro de envíos. ' or . = ' Declaro bajo juramento los productos escritos en el registro de envíos. ')]</value>
      <webElementGuid>35394190-eda7-46e0-8bc6-56d2327aabb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/ 1234.00'])[1]/following::label[2]</value>
      <webElementGuid>ff22a96d-5a05-4ba9-8d6a-143494644045</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
