<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Envo de cajas o paquetescon un peso mxi_37770f</name>
   <tag></tag>
   <elementGuidId>e51590e8-295d-472c-8ca2-5b59feba815d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img_sobre']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#img_sobre</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7b37bb00-7796-4c94-891d-f09e78ecf637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img_sobre</value>
      <webElementGuid>2b3485f8-7067-4fd5-b062-22bfb2813e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev-registrodeenvios.olvacourier.com/assets/img/sobre_v3.png</value>
      <webElementGuid>588c69c7-8be6-4ebe-9341-5aac4d86aa30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>e932ec28-9688-4e43-a220-f933d464cc8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>f0164b7e-00ee-4c6f-a7e1-a0cdc57b940e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pointer</value>
      <webElementGuid>e22e6eb8-057c-4230-a3d8-757fe56ebc5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img_sobre&quot;)</value>
      <webElementGuid>437e98b1-87d0-46f9-ac93-7b2015ba3bb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img_sobre']</value>
      <webElementGuid>dbee99a5-faf5-470d-8fb1-2aec989d3a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//figure[@id='contenedor_sobre']/img</value>
      <webElementGuid>59fa0868-f96f-4ccb-8cb1-6126f234e9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev-registrodeenvios.olvacourier.com/assets/img/sobre_v3.png')]</value>
      <webElementGuid>f7ffad96-fc08-4a74-b975-3633e4d1134b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/label/div/figure/img</value>
      <webElementGuid>50fe54b5-2958-4c42-84c6-ce012d53e182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'img_sobre' and @src = 'https://dev-registrodeenvios.olvacourier.com/assets/img/sobre_v3.png']</value>
      <webElementGuid>532770f8-4a3a-419a-bb46-5e70562430b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
