<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CUSCO</name>
   <tag></tag>
   <elementGuidId>10d8a227-bac2-422d-a348-e0ac1c00afcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.btn-group.bootstrap-select.form-control.open > div.dropdown-menu.open > ul.dropdown-menu.inner.selectpicker > li:nth-of-type(17) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div_lima']/div/div/ul/li[17]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>11de5283-7624-410f-b9bc-e7bd3e54d1d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f84fa492-cc08-4d75-a8c9-b948085d57ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-normalized-text</name>
      <type>Main</type>
      <value>&lt;span class=&quot;text&quot;>
                                    CUSCO&lt;/span></value>
      <webElementGuid>34ceb53a-d1a6-4bd4-9503-faeb3696a8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    CUSCO</value>
      <webElementGuid>0558ce1c-e361-462c-b05c-3a802e9ec8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_lima&quot;)/div[@class=&quot;btn-group bootstrap-select form-control open&quot;]/div[@class=&quot;dropdown-menu open&quot;]/ul[@class=&quot;dropdown-menu inner selectpicker&quot;]/li[17]/a[1]</value>
      <webElementGuid>80a3a770-ce55-488f-8642-a565a583a902</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_lima']/div/div/ul/li[17]/a</value>
      <webElementGuid>73b2ed9c-265c-4b39-8046-c733bb373d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AREQUIPA'])[6]/following::a[1]</value>
      <webElementGuid>c5215917-d9d8-481e-8cc9-687f7b2fa677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TACNA'])[4]/following::a[2]</value>
      <webElementGuid>1d8bcf91-58a1-40a0-a971-06975b025175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LIMA'])[5]/preceding::a[1]</value>
      <webElementGuid>b8b48653-67ec-46aa-bb87-f8d9d765803a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/ul/li[17]/a</value>
      <webElementGuid>5fa954d5-68ec-49ef-81ae-64ca50e94133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '
                                    CUSCO' or . = '
                                    CUSCO')]</value>
      <webElementGuid>02e6f5ee-3ab5-453b-a7df-2fabd919a4f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
