<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CONTINUAR</name>
   <tag></tag>
   <elementGuidId>5b37996a-d703-4608-8d1d-cc2b19384098</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_guardar_datos_personales</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_guardar_datos_personales']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>008a6b20-7c6c-4936-af18-64b6e669f85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_guardar_datos_personales</value>
      <webElementGuid>34c27aae-f436-4b6f-8d09-e730a9be0a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ebdc922c-3bd3-47f9-8ddf-420c491a7c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning mt-10</value>
      <webElementGuid>874e9668-bb33-46c9-8cf8-8aa729d0cd58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTINUAR</value>
      <webElementGuid>8d5b1077-6d99-4db6-88df-e6ad625523dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_guardar_datos_personales&quot;)</value>
      <webElementGuid>fda7aab7-38e4-4bf4-a2a3-a1f26fd6ac45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_guardar_datos_personales']</value>
      <webElementGuid>e8759e7a-27b0-41b3-82c0-13d1f5f86677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_quien_envia']/button</value>
      <webElementGuid>410505ec-c0ad-4998-a9d6-facb155b659f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QAQA'])[1]/following::button[1]</value>
      <webElementGuid>3325b57a-35f1-4009-ae6b-5b67f2d49d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARNÉ EXT.'])[2]/following::button[1]</value>
      <webElementGuid>d3268779-bf5a-4895-8823-efe98fe7ac1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Validación del primer apellido'])[1]/preceding::button[1]</value>
      <webElementGuid>5ff32e10-c205-4543-a97f-f87f55fed0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='El apellido ingresado debe ser igual al registrado en su DNI'])[1]/preceding::button[2]</value>
      <webElementGuid>c1e51cc4-3185-4acc-99f6-6de0d9038033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CONTINUAR']/parent::*</value>
      <webElementGuid>7e3e3317-10ce-4c4c-9fb4-f61d96a2c7e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>1a4627ba-ac93-4082-ae18-347b55983721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_guardar_datos_personales' and @type = 'button' and (text() = 'CONTINUAR' or . = 'CONTINUAR')]</value>
      <webElementGuid>6217dff8-e4a4-444d-aad3-fc7fc658b25f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
