<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OK_modal-backdrop fade in</name>
   <tag></tag>
   <elementGuidId>13d691fa-3162-4abd-b794-3426ff919a9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.modal-backdrop.fade.in</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c6876fb3-61d9-496a-a12f-66c1bd0888e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-backdrop fade in</value>
      <webElementGuid>0bd87edb-f34b-47db-b082-acc38699e406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;modal-backdrop fade in&quot;]</value>
      <webElementGuid>b9156e48-9d03-4c27-977c-a37fa88ddaf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]</value>
      <webElementGuid>3c7f2f39-6197-4088-9527-f04182c30f7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
