<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Editar</name>
   <tag></tag>
   <elementGuidId>e7d68ed4-6562-4a9f-b9c5-d9e16597f65a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.button.icon-action-envio.edit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@onclick='parentNode.submit();']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bf0cfc2e-bccc-4058-a9db-cbad52532d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn button icon-action-envio edit</value>
      <webElementGuid>6cfc33f6-275a-4e89-b9a5-a58dd61f7ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>parentNode.submit();</value>
      <webElementGuid>99ce03c3-1bcd-4c39-8277-249f460573e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Editar</value>
      <webElementGuid>1a8ff469-eab7-4665-ad00-2cccc01593ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blueTable_wrapper&quot;)/table[@id=&quot;blueTable&quot;]/tbody[1]/tr[@class=&quot;odd&quot;]/td[1]/form[@class=&quot;btn-edit-acciones&quot;]/button[@class=&quot;btn button icon-action-envio edit&quot;]</value>
      <webElementGuid>846771a3-d201-49d3-ac78-9b0ede6551d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@onclick='parentNode.submit();']</value>
      <webElementGuid>fe08f415-28fb-468c-bea6-67e28ff9630d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='blueTable']/tbody/tr/td/form/button</value>
      <webElementGuid>fcede3c3-20bd-48c0-9634-c5a6fbd5937c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/ 20.00'])[1]/following::button[1]</value>
      <webElementGuid>2b7777c7-8c99-434d-b61b-471856c60e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/ 0.00'])[1]/following::button[1]</value>
      <webElementGuid>95248cca-1771-4ee3-be19-793ceaf63573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar'])[1]/preceding::button[1]</value>
      <webElementGuid>e5b709ac-b7c5-4267-8e26-ff38d3f9638b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anterior'])[1]/preceding::button[2]</value>
      <webElementGuid>573ac882-c7fe-4df5-a1a9-96e6e4db2645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Editar']/parent::*</value>
      <webElementGuid>7c536b6e-3fe3-41de-b23d-1bc37990cff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>48e9f217-e3d8-466e-a34e-a8dbfbcb6167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Editar' or . = 'Editar')]</value>
      <webElementGuid>f2d09c9d-2852-418d-b87f-45bd02635a4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
