<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_termsUsoyPriv</name>
   <tag></tag>
   <elementGuidId>0fe6a4a1-c4ea-478f-90a3-a0b4c3252eaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#verTerminos</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='verTerminos']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6a339baa-b2f7-472b-b72f-4ef5154ed3a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verTerminos</value>
      <webElementGuid>01d35989-c780-4eb7-aa34-bffdfed1cf21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>74d2cae8-9e63-49a3-a3ca-9cfa5e1ca517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>términos de uso y políticas de privacidad</value>
      <webElementGuid>551d2bd5-f521-4347-984f-36d3f65e7c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verTerminos&quot;)</value>
      <webElementGuid>62e54b97-e7f1-4a1d-8cd4-c10d2331a560</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='verTerminos']</value>
      <webElementGuid>ae1b0864-5685-4f24-9094-234aa7470f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_tipo_envio']/p/label/a</value>
      <webElementGuid>e41ca0c6-38e9-4c14-bf53-734f4dcef3fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'términos de uso y políticas de privacidad')]</value>
      <webElementGuid>c3f9e559-46bf-4808-be56-8d6a86d780cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUAR'])[1]/preceding::a[1]</value>
      <webElementGuid>18b56baa-ee7d-4782-b063-b9539b830303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='términos de uso y políticas de privacidad']/parent::*</value>
      <webElementGuid>b68a988d-1e48-48a3-b8ec-e53809f7bd97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>8c99edc3-5752-4e1d-8344-77cc331fff9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/a</value>
      <webElementGuid>2d11aa9e-cbbd-473d-84e7-2769a1fd7263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'verTerminos' and @href = '#' and (text() = 'términos de uso y políticas de privacidad' or . = 'términos de uso y políticas de privacidad')]</value>
      <webElementGuid>9b75caed-a892-43f7-84bd-1a8c1a71867b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
