<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CHOCOPE - CHOCOPE - CA DIEGO DE MORA NRO 235 CHOCOPE (AL COSTADO DEL HOTEL CESAR PALACE)</name>
   <tag></tag>
   <elementGuidId>fe55a61b-3744-48d5-910b-4870abb0ed67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container_cbo_tienda']/div/div/ul/li[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>52b5eb9e-e09d-4118-9c4b-82b6be9f19fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c74d46a1-5bc8-4393-8161-d4c5f0838dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHOCOPE - CHOCOPE - CA DIEGO DE MORA NRO 235 CHOCOPE (AL COSTADO DEL HOTEL CESAR PALACE)</value>
      <webElementGuid>1485436f-2926-4426-ab38-7cd60e363149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container_cbo_tienda&quot;)/div[@class=&quot;btn-group bootstrap-select form-control msg_alert_tt open&quot;]/div[@class=&quot;dropdown-menu open&quot;]/ul[@class=&quot;dropdown-menu inner selectpicker&quot;]/li[2]/a[1]/span[@class=&quot;text&quot;]</value>
      <webElementGuid>e032ec0b-ffba-4458-a5f9-bd5d016de3cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container_cbo_tienda']/div/div/ul/li[2]/a/span</value>
      <webElementGuid>73f96490-577e-4bb0-a8b2-eb74778c8262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tienda'])[3]/following::span[2]</value>
      <webElementGuid>0155c537-c656-406e-9b08-24f80b00d57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tienda'])[2]/following::span[4]</value>
      <webElementGuid>f341286e-2872-40c0-a760-047bbb3ca879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Envío:'])[1]/preceding::span[2]</value>
      <webElementGuid>6d35a126-1173-4e83-9e6f-77024b4593ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TARJETAS'])[1]/preceding::span[2]</value>
      <webElementGuid>7273621b-424f-4e43-92c0-b57e73e0d218</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/ul/li[2]/a/span</value>
      <webElementGuid>94e9508d-50b2-42ea-9989-8a9614ba5c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'CHOCOPE - CHOCOPE - CA DIEGO DE MORA NRO 235 CHOCOPE (AL COSTADO DEL HOTEL CESAR PALACE)' or . = 'CHOCOPE - CHOCOPE - CA DIEGO DE MORA NRO 235 CHOCOPE (AL COSTADO DEL HOTEL CESAR PALACE)')]</value>
      <webElementGuid>8bd19ed5-6253-4557-997e-4b62ce4a871a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
