<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_VIRU - TIENDA VIRU - VIRU - AV PANAMERICANA NORTE NRO 381</name>
   <tag></tag>
   <elementGuidId>9bc1393a-6229-4eb4-868e-df947914a32e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container_cbo_tienda']/div/div/ul/li[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>51dd19a1-d6cd-493c-9180-0d81d5f4705d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5654e6e8-b9f4-4acd-a9fe-b960c6a42238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VIRU - TIENDA VIRU - VIRU - AV PANAMERICANA NORTE NRO 381 </value>
      <webElementGuid>06a4c09b-19e1-4905-9e8a-16a7c35551f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container_cbo_tienda&quot;)/div[@class=&quot;btn-group bootstrap-select form-control msg_alert_tt open&quot;]/div[@class=&quot;dropdown-menu open&quot;]/ul[@class=&quot;dropdown-menu inner selectpicker&quot;]/li[2]/a[1]/span[@class=&quot;text&quot;]</value>
      <webElementGuid>4f25cd72-0795-41df-9fb9-5b97daede98a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container_cbo_tienda']/div/div/ul/li[2]/a/span</value>
      <webElementGuid>cc1b4da9-d611-4448-a1d2-18ff217cc2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tienda'])[3]/following::span[2]</value>
      <webElementGuid>81726695-1cff-458e-98b7-98e1acc66d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tienda'])[2]/following::span[4]</value>
      <webElementGuid>f9a9941a-f2dd-4058-9ca3-6fbb6020540f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIRU - VIRU - AV PANAMERICANA NORTE NRO 381'])[2]/preceding::span[2]</value>
      <webElementGuid>b20938a3-d68a-41dc-80b8-ae4cd1f01ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Envío:'])[1]/preceding::span[4]</value>
      <webElementGuid>04105df0-53c0-4581-9331-82b086034885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/ul/li[2]/a/span</value>
      <webElementGuid>53431831-9acb-48b4-8a0f-8185a2661426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'VIRU - TIENDA VIRU - VIRU - AV PANAMERICANA NORTE NRO 381 ' or . = 'VIRU - TIENDA VIRU - VIRU - AV PANAMERICANA NORTE NRO 381 ')]</value>
      <webElementGuid>44c3e7c7-f147-4271-bf4b-61c81992c1c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
